site_name: {{ cookiecutter.name }}
site_description: {{ cookiecutter.description }}
site_url: https://github.com/{{ cookiecutter.github_repo }}

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deeppurple
      accent: deeppurple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

repo_name: {{ cookiecutter.github_repo }}
repo_url: https://github.com/{{ cookiecutter.github_repo }}
edit_uri: ""

nav:
    - Introduction: "index.md"

markdown_extensions:
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences